name: PR Notification
on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Get Changed Files & PR Description
        id: pr_info
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}/files")

          ADDED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.status=="added") | .filename' | paste -sd ", " -)
          MODIFIED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.status=="modified") | .filename' | paste -sd ", " -)
          DELETED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.status=="removed") | .filename' | paste -sd ", " -)

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_USER="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          MESSAGE="New Pull Request: **$PR_TITLE** by **$PR_USER**.%0A%0A"
          MESSAGE+="ðŸ”— **Review here:** [$PR_URL]($PR_URL)%0A%0A"

          if [[ -n "$PR_DESCRIPTION" ]]; then
            MESSAGE+="ðŸ“ **Description:** $PR_DESCRIPTION%0A%0A"
          fi

          if [[ -n "$ADDED_FILES" ]]; then
            MESSAGE+="ðŸ“‚ **Files Added:** $ADDED_FILES%0A"
          fi

          if [[ -n "$MODIFIED_FILES" ]]; then
            MESSAGE+="âœï¸ **Files Modified:** $MODIFIED_FILES%0A"
          fi

          if [[ -n "$DELETED_FILES" ]]; then
            MESSAGE+="ðŸ—‘ï¸ **Files Deleted:** $DELETED_FILES%0A"
          fi

          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Send Notification to Teams
        run: |
          curl -H "Content-Type: application/json" -d "{
            \"text\": \"${{ env.MESSAGE }}\"
          }" "https://northerndata.webhook.office.com/webhookb2/0e8a6750-d437-43ad-bbed-54081be47e82@174c7352-9c5c-4558-b848-be140b444e7d/IncomingWebhook/4ef5202394ad4526b10205b0fe43c8a6/6acd2e93-9d80-4d4b-8481-695c39e6b878/V2YQXCJDEMEG9arYvJcOr2zX49FEqxKco0Tlc6uPibm9U1"
